export interface IMGPS {
  ID: any,
  Title: any,
  EmpID: any,
  EmpName: any,
  EmpNameEmail:any,
  Department: any,
  CostCenter: any,  
  Items: any,
  Status: any,
  Created: any,
  Total: any,
  Date: any,
  AttachmentFiles: any,
  Summary: any,  
  Stage: any,
  NextApproverEmpID: any,
  DelegateApproverEmpID: any,
  RGPReturnDate: any,
  MaterialFor: any,
  TotalAmt: any,
  AssetIndicator: any,
  ShipmentMode: any,
  ShipmentType: any,
  DRNo: any,
  FreightChargesBy: any,
  FreightChargesAmt: any,
  ConsigneeDetails: any,
  InitiatorDetails: any,
  Purpose: any,
  RejectWithdrawnComment: any,
  ReworkComment: any,
  flagEmail: any,
  NextApprover: any,
  DelegatorApprover: any,
  ApprovalFlow: any,
  LRNo: any,
  LRDate: any,
  CarrierDetails: any,
  ReturnLRNo: any,
  ReturnLRDate: any,
  ExitDate: any,
  EntryDate: any,
  GeneralAttachmentList: any,
  isSecurityPrint: any,
  requiredDateExtension: any,
  SendEmail:any,
  ReqNo:any,
  Author: any,
  DmtAssocaite:any,
  Price?:any
}
